export const imagesData: {[key: string]: string} = {
  automotive: require('../../assets/images/categories/automotive.jpg'),
  fragrances: require('../../assets/images/categories/fragrances.jpg'),
  furniture: require('../../assets/images/categories/furniture.jpg'),
  groceries: require('../../assets/images/categories/groceries.jpg'),
  'home-decoration': require('../../assets/images/categories/home-decoration.jpg'),
  laptops: require('../../assets/images/categories/laptops.jpg'),
  lighting: require('../../assets/images/categories/lighting.jpg'),
  'mens-shirts': require('../../assets/images/categories/mens-shirts.jpg'),
  'mens-watches': require('../../assets/images/categories/mens-watches.jpg'),
  'mens-shoes': require('../../assets/images/categories/mens-shoes.jpg'),
  motorcycle: require('../../assets/images/categories/motorcycle.jpg'),
  skincare: require('../../assets/images/categories/skincare.jpg'),
  smartphones: require('../../assets/images/categories/smartphones.jpg'),
  sunglasses: require('../../assets/images/categories/sunglasses.jpg'),
  tops: require('../../assets/images/categories/tops.jpg'),
  'womens-bags': require('../../assets/images/categories/womens-bags.jpg'),
  'womens-dresses': require('../../assets/images/categories/womens-dresses.jpg'),
  'womens-jewellery': require('../../assets/images/categories/womens-jewellery.jpg'),
  'womens-shoes': require('../../assets/images/categories/womens-shoes.jpg'),
  'womens-watches': require('../../assets/images/categories/womens-watches.jpg'),
  FirstBanner: require('../../assets/images/banner1.jpg'),
  SecondBanner: require('../../assets/images/banner2.jpg'),
  ThirdBanner: require('../../assets/images/banner3.jpg'),
};
